// This file is auto-generated by @hey-api/openapi-ts

export type Event = {
    startTime: Date;
    title: string;
    subTitle?: string;
    image: Image;
};

export type Image = {
    title: string;
    content: string;
    mimeType: string;
};

export type Presentation = {
    countdownEnd: Date;
    title: string;
    subTitle?: string;
    events: Array<Event>;
    countdownInSeconds: number;
};

export type GetPresentationResponse = (Presentation);

export type GetPresentationError = unknown;

export type $OpenApiTs = {
    '/presentation': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Presentation;
            };
        };
    };
};