// This file is auto-generated by @hey-api/openapi-ts

export type Presentation = {
    id: number;
    countdownEnd: string;
    title: string;
    subTitle?: string;
    countdownInSeconds: number;
};

export type Event = {
    id: number;
    startTime: string;
    title: string;
    subTitle?: string;
    image?: Image;
};

export type Image = {
    title: string;
    content: string;
    mimeType: string;
};

export type GetPresentationResponse = (Presentation);

export type GetPresentationError = unknown;

export type GetEventResponse = (Event);

export type GetEventError = unknown;

export type $OpenApiTs = {
    '/presentation': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Presentation;
            };
        };
    };
    '/event': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Event;
            };
        };
    };
};